// Auto-generated by Supabase MCP — do not edit manually.
// To regenerate: use the supabase MCP generate_typescript_types tool.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      activity_logs: {
        Row: {
          action: string
          created_at: string
          description: string
          enrollment_id: string | null
          entity_id: string | null
          entity_name: string | null
          entity_type: string
          id: string
          lead_id: string | null
          metadata: Json | null
          student_id: string | null
          user_id: string | null
          user_name: string
        }
        Insert: {
          action: string
          created_at?: string
          description: string
          enrollment_id?: string | null
          entity_id?: string | null
          entity_name?: string | null
          entity_type: string
          id?: string
          lead_id?: string | null
          metadata?: Json | null
          student_id?: string | null
          user_id?: string | null
          user_name?: string
        }
        Update: {
          action?: string
          created_at?: string
          description?: string
          enrollment_id?: string | null
          entity_id?: string | null
          entity_name?: string | null
          entity_type?: string
          id?: string
          lead_id?: string | null
          metadata?: Json | null
          student_id?: string | null
          user_id?: string | null
          user_name?: string
        }
        Relationships: [
          {
            foreignKeyName: "activity_logs_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "enrollments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_logs_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_logs_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
        ]
      }
      agent_config: {
        Row: {
          id: string
          is_active: boolean
          knowledge: string
          model: string
          system_prompt: string
          updated_at: string | null
          updated_by: string | null
          welcome_message: string
        }
        Insert: {
          id?: string
          is_active?: boolean
          knowledge?: string
          model?: string
          system_prompt?: string
          updated_at?: string | null
          updated_by?: string | null
          welcome_message?: string
        }
        Update: {
          id?: string
          is_active?: boolean
          knowledge?: string
          model?: string
          system_prompt?: string
          updated_at?: string | null
          updated_by?: string | null
          welcome_message?: string
        }
        Relationships: [
          {
            foreignKeyName: "agent_config_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          changed_by: string | null
          created_at: string
          id: string
          metadata: Json | null
          new_values: Json | null
          old_values: Json | null
          record_id: string
          table_name: string
        }
        Insert: {
          action: string
          changed_by?: string | null
          created_at?: string
          id?: string
          metadata?: Json | null
          new_values?: Json | null
          old_values?: Json | null
          record_id: string
          table_name: string
        }
        Update: {
          action?: string
          changed_by?: string | null
          created_at?: string
          id?: string
          metadata?: Json | null
          new_values?: Json | null
          old_values?: Json | null
          record_id?: string
          table_name?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      certificates: {
        Row: {
          created_at: string
          deleted_at: string | null
          document_url: string | null
          enrollment_id: string
          id: string
          issued_at: string | null
          issued_by: string | null
          status: Database["public"]["Enums"]["certificate_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          deleted_at?: string | null
          document_url?: string | null
          enrollment_id: string
          id?: string
          issued_at?: string | null
          issued_by?: string | null
          status?: Database["public"]["Enums"]["certificate_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          deleted_at?: string | null
          document_url?: string | null
          enrollment_id?: string
          id?: string
          issued_at?: string | null
          issued_by?: string | null
          status?: Database["public"]["Enums"]["certificate_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "certificates_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "enrollments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "certificates_issued_by_fkey"
            columns: ["issued_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      contract_events: {
        Row: {
          contract_id: string
          decline_reason: string | null
          email: string | null
          enrollment_id: string | null
          event_type: string
          id: string
          occurred_at: string
        }
        Insert: {
          contract_id: string
          decline_reason?: string | null
          email?: string | null
          enrollment_id?: string | null
          event_type: string
          id?: string
          occurred_at?: string
        }
        Update: {
          contract_id?: string
          decline_reason?: string | null
          email?: string | null
          enrollment_id?: string | null
          event_type?: string
          id?: string
          occurred_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "contract_events_contract_id_fkey"
            columns: ["contract_id"]
            isOneToOne: false
            referencedRelation: "contracts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contract_events_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "enrollments"
            referencedColumns: ["id"]
          },
        ]
      }
      contracts: {
        Row: {
          amount: number
          cash_amount: number | null
          cash_method: Database["public"]["Enums"]["cash_method"] | null
          created_at: string
          created_by: string
          declined_at: string | null
          deleted_at: string | null
          document_url: string | null
          docuseal_signing_url: string | null
          docuseal_submission_id: string | null
          enrollment_id: string | null
          financed_amount: number | null
          financer: Database["public"]["Enums"]["financer"] | null
          id: string
          opportunity_id: string | null
          payment_type: Database["public"]["Enums"]["payment_type"] | null
          sent_at: string | null
          signed_at: string | null
          status: Database["public"]["Enums"]["contract_status"]
          student_id: string | null
          updated_at: string
        }
        Insert: {
          amount: number
          cash_amount?: number | null
          cash_method?: Database["public"]["Enums"]["cash_method"] | null
          created_at?: string
          created_by: string
          declined_at?: string | null
          deleted_at?: string | null
          document_url?: string | null
          docuseal_signing_url?: string | null
          docuseal_submission_id?: string | null
          enrollment_id?: string | null
          financed_amount?: number | null
          financer?: Database["public"]["Enums"]["financer"] | null
          id?: string
          opportunity_id?: string | null
          payment_type?: Database["public"]["Enums"]["payment_type"] | null
          sent_at?: string | null
          signed_at?: string | null
          status?: Database["public"]["Enums"]["contract_status"]
          student_id?: string | null
          updated_at?: string
        }
        Update: {
          amount?: number
          cash_amount?: number | null
          cash_method?: Database["public"]["Enums"]["cash_method"] | null
          created_at?: string
          created_by?: string
          declined_at?: string | null
          deleted_at?: string | null
          document_url?: string | null
          docuseal_signing_url?: string | null
          docuseal_submission_id?: string | null
          enrollment_id?: string | null
          financed_amount?: number | null
          financer?: Database["public"]["Enums"]["financer"] | null
          id?: string
          opportunity_id?: string | null
          payment_type?: Database["public"]["Enums"]["payment_type"] | null
          sent_at?: string | null
          signed_at?: string | null
          status?: Database["public"]["Enums"]["contract_status"]
          student_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "contracts_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contracts_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "enrollments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contracts_opportunity_id_fkey"
            columns: ["opportunity_id"]
            isOneToOne: false
            referencedRelation: "opportunities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contracts_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
        ]
      }
      courses: {
        Row: {
          code: string | null
          created_at: string
          description: string | null
          duration_hours: number | null
          id: string
          is_active: boolean
          is_certificado_profesionalidad: boolean
          is_fundae: boolean
          name: string
          updated_at: string
        }
        Insert: {
          code?: string | null
          created_at?: string
          description?: string | null
          duration_hours?: number | null
          id?: string
          is_active?: boolean
          is_certificado_profesionalidad?: boolean
          is_fundae?: boolean
          name: string
          updated_at?: string
        }
        Update: {
          code?: string | null
          created_at?: string
          description?: string | null
          duration_hours?: number | null
          id?: string
          is_active?: boolean
          is_certificado_profesionalidad?: boolean
          is_fundae?: boolean
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      enrollments: {
        Row: {
          course_id: string
          created_at: string
          created_by: string
          deleted_at: string | null
          duration_months: number | null
          end_date: string | null
          enrollment_date: string
          enrollment_number: number
          id: string
          notes: string | null
          platform_id: string | null
          start_date: string | null
          status: Database["public"]["Enums"]["enrollment_status"]
          student_id: string
          tutor_id: string | null
          updated_at: string
          validated_at: string | null
          validated_by: string | null
        }
        Insert: {
          course_id: string
          created_at?: string
          created_by: string
          deleted_at?: string | null
          duration_months?: number | null
          end_date?: string | null
          enrollment_date?: string
          enrollment_number?: number
          id?: string
          notes?: string | null
          platform_id?: string | null
          start_date?: string | null
          status?: Database["public"]["Enums"]["enrollment_status"]
          student_id: string
          tutor_id?: string | null
          updated_at?: string
          validated_at?: string | null
          validated_by?: string | null
        }
        Update: {
          course_id?: string
          created_at?: string
          created_by?: string
          deleted_at?: string | null
          duration_months?: number | null
          end_date?: string | null
          enrollment_date?: string
          enrollment_number?: number
          id?: string
          notes?: string | null
          platform_id?: string | null
          start_date?: string | null
          status?: Database["public"]["Enums"]["enrollment_status"]
          student_id?: string
          tutor_id?: string | null
          updated_at?: string
          validated_at?: string | null
          validated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "enrollments_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "enrollments_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "enrollments_platform_id_fkey"
            columns: ["platform_id"]
            isOneToOne: false
            referencedRelation: "platforms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "enrollments_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "enrollments_tutor_id_fkey"
            columns: ["tutor_id"]
            isOneToOne: false
            referencedRelation: "tutors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "enrollments_validated_by_fkey"
            columns: ["validated_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_interactions: {
        Row: {
          contact_type: string
          created_at: string
          followup_date: string
          id: string
          lead_id: string
          next_followup_date: string | null
          notes: string
          user_id: string
        }
        Insert: {
          contact_type: string
          created_at?: string
          followup_date?: string
          id?: string
          lead_id: string
          next_followup_date?: string | null
          notes: string
          user_id: string
        }
        Update: {
          contact_type?: string
          created_at?: string
          followup_date?: string
          id?: string
          lead_id?: string
          next_followup_date?: string | null
          notes?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "lead_interactions_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_interactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      leads: {
        Row: {
          address: string | null
          birth_date: string | null
          converted_to_student_id: string | null
          created_at: string
          dni_nie: string | null
          email: string | null
          full_name: string
          id: string
          interested_course: string | null
          notes: string | null
          owner_id: string | null
          phone: string | null
          postal_code: string | null
          province: string | null
          source: Database["public"]["Enums"]["lead_source"]
          status: Database["public"]["Enums"]["lead_status"]
          updated_at: string
        }
        Insert: {
          address?: string | null
          birth_date?: string | null
          converted_to_student_id?: string | null
          created_at?: string
          dni_nie?: string | null
          email?: string | null
          full_name: string
          id?: string
          interested_course?: string | null
          notes?: string | null
          owner_id?: string | null
          phone?: string | null
          postal_code?: string | null
          province?: string | null
          source?: Database["public"]["Enums"]["lead_source"]
          status?: Database["public"]["Enums"]["lead_status"]
          updated_at?: string
        }
        Update: {
          address?: string | null
          birth_date?: string | null
          converted_to_student_id?: string | null
          created_at?: string
          dni_nie?: string | null
          email?: string | null
          full_name?: string
          id?: string
          interested_course?: string | null
          notes?: string | null
          owner_id?: string | null
          phone?: string | null
          postal_code?: string | null
          province?: string | null
          source?: Database["public"]["Enums"]["lead_source"]
          status?: Database["public"]["Enums"]["lead_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "fk_leads_converted_student"
            columns: ["converted_to_student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          created_at: string
          id: string
          is_read: boolean
          message: string
          read_at: string | null
          related_entity_id: string | null
          related_entity_type: string | null
          title: string
          type: Database["public"]["Enums"]["notification_type"]
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_read?: boolean
          message: string
          read_at?: string | null
          related_entity_id?: string | null
          related_entity_type?: string | null
          title: string
          type: Database["public"]["Enums"]["notification_type"]
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          is_read?: boolean
          message?: string
          read_at?: string | null
          related_entity_id?: string | null
          related_entity_type?: string | null
          title?: string
          type?: Database["public"]["Enums"]["notification_type"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      opportunities: {
        Row: {
          closed_at: string | null
          course_id: string | null
          created_at: string
          estimated_amount: number | null
          id: string
          lead_id: string
          owner_id: string
          stage_id: string
          updated_at: string
        }
        Insert: {
          closed_at?: string | null
          course_id?: string | null
          created_at?: string
          estimated_amount?: number | null
          id?: string
          lead_id: string
          owner_id: string
          stage_id: string
          updated_at?: string
        }
        Update: {
          closed_at?: string | null
          course_id?: string | null
          created_at?: string
          estimated_amount?: number | null
          id?: string
          lead_id?: string
          owner_id?: string
          stage_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "opportunities_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "opportunities_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "opportunities_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "opportunities_stage_id_fkey"
            columns: ["stage_id"]
            isOneToOne: false
            referencedRelation: "pipeline_stages"
            referencedColumns: ["id"]
          },
        ]
      }
      pipeline_stages: {
        Row: {
          code: string
          created_at: string
          display_order: number
          id: string
          is_lost: boolean
          is_won: boolean
          name: string
        }
        Insert: {
          code: string
          created_at?: string
          display_order: number
          id?: string
          is_lost?: boolean
          is_won?: boolean
          name: string
        }
        Update: {
          code?: string
          created_at?: string
          display_order?: number
          id?: string
          is_lost?: boolean
          is_won?: boolean
          name?: string
        }
        Relationships: []
      }
      platforms: {
        Row: {
          code: string
          created_at: string
          id: string
          is_active: boolean
          metadata: Json
          name: string
        }
        Insert: {
          code: string
          created_at?: string
          id?: string
          is_active?: boolean
          metadata?: Json
          name: string
        }
        Update: {
          code?: string
          created_at?: string
          id?: string
          is_active?: boolean
          metadata?: Json
          name?: string
        }
        Relationships: []
      }
      roles: {
        Row: {
          code: Database["public"]["Enums"]["app_role"]
          created_at: string
          description: string | null
          id: string
          name: string
        }
        Insert: {
          code: Database["public"]["Enums"]["app_role"]
          created_at?: string
          description?: string | null
          id?: string
          name: string
        }
        Update: {
          code?: Database["public"]["Enums"]["app_role"]
          created_at?: string
          description?: string | null
          id?: string
          name?: string
        }
        Relationships: []
      }
      student_attachments: {
        Row: {
          certificate_id: string | null
          created_at: string
          enrollment_id: string | null
          file_name: string
          file_path: string
          file_size: number | null
          id: string
          lead_id: string | null
          mime_type: string | null
          student_id: string | null
          title: string | null
          uploaded_by: string
        }
        Insert: {
          certificate_id?: string | null
          created_at?: string
          enrollment_id?: string | null
          file_name: string
          file_path: string
          file_size?: number | null
          id?: string
          lead_id?: string | null
          mime_type?: string | null
          student_id?: string | null
          title?: string | null
          uploaded_by: string
        }
        Update: {
          certificate_id?: string | null
          created_at?: string
          enrollment_id?: string | null
          file_name?: string
          file_path?: string
          file_size?: number | null
          id?: string
          lead_id?: string | null
          mime_type?: string | null
          student_id?: string | null
          title?: string | null
          uploaded_by?: string
        }
        Relationships: [
          {
            foreignKeyName: "student_attachments_certificate_id_fkey"
            columns: ["certificate_id"]
            isOneToOne: false
            referencedRelation: "certificates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "student_attachments_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "enrollments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "student_attachments_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "student_attachments_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "student_attachments_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      students: {
        Row: {
          address: string | null
          assigned_to: string | null
          birth_date: string | null
          created_at: string
          created_by: string
          deleted_at: string | null
          dni_nie: string
          email: string
          first_name: string
          full_name: string
          id: string
          last_name: string
          lead_id: string | null
          phone: string | null
          postal_code: string | null
          province: string | null
          status: Database["public"]["Enums"]["student_status"]
          student_number: number
          updated_at: string
        }
        Insert: {
          address?: string | null
          assigned_to?: string | null
          birth_date?: string | null
          created_at?: string
          created_by: string
          deleted_at?: string | null
          dni_nie: string
          email: string
          first_name: string
          full_name: string
          id?: string
          last_name: string
          lead_id?: string | null
          phone?: string | null
          postal_code?: string | null
          province?: string | null
          status?: Database["public"]["Enums"]["student_status"]
          student_number?: number
          updated_at?: string
        }
        Update: {
          address?: string | null
          assigned_to?: string | null
          birth_date?: string | null
          created_at?: string
          created_by?: string
          deleted_at?: string | null
          dni_nie?: string
          email?: string
          first_name?: string
          full_name?: string
          id?: string
          last_name?: string
          lead_id?: string | null
          phone?: string | null
          postal_code?: string | null
          province?: string | null
          status?: Database["public"]["Enums"]["student_status"]
          student_number?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "students_assigned_to_fkey"
            columns: ["assigned_to"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "students_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "students_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      tutor_followups: {
        Row: {
          contact_type: Database["public"]["Enums"]["contact_type"]
          created_at: string
          created_by: string | null
          enrollment_id: string
          followup_date: string
          id: string
          notes: string
          student_status_snapshot: Database["public"]["Enums"]["followup_student_status"]
          tutor_id: string | null
        }
        Insert: {
          contact_type: Database["public"]["Enums"]["contact_type"]
          created_at?: string
          created_by?: string | null
          enrollment_id: string
          followup_date?: string
          id?: string
          notes: string
          student_status_snapshot: Database["public"]["Enums"]["followup_student_status"]
          tutor_id?: string | null
        }
        Update: {
          contact_type?: Database["public"]["Enums"]["contact_type"]
          created_at?: string
          created_by?: string | null
          enrollment_id?: string
          followup_date?: string
          id?: string
          notes?: string
          student_status_snapshot?: Database["public"]["Enums"]["followup_student_status"]
          tutor_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tutor_followups_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tutor_followups_enrollment_id_fkey"
            columns: ["enrollment_id"]
            isOneToOne: false
            referencedRelation: "enrollments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tutor_followups_tutor_id_fkey"
            columns: ["tutor_id"]
            isOneToOne: false
            referencedRelation: "tutors"
            referencedColumns: ["id"]
          },
        ]
      }
      tutors: {
        Row: {
          created_at: string
          id: string
          is_active: boolean
          specialty: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_active?: boolean
          specialty?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          is_active?: boolean
          specialty?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tutors_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          avatar_url: string | null
          created_at: string
          email: string
          full_name: string
          id: string
          is_active: boolean
          phone: string | null
          role: Database["public"]["Enums"]["app_role"]
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          email: string
          full_name: string
          id: string
          is_active?: boolean
          phone?: string | null
          role: Database["public"]["Enums"]["app_role"]
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          email?: string
          full_name?: string
          id?: string
          is_active?: boolean
          phone?: string | null
          role?: Database["public"]["Enums"]["app_role"]
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      comercial_can_see_enrollment: {
        Args: { p_student_id: string }
        Returns: boolean
      }
      current_user_role: {
        Args: never
        Returns: Database["public"]["Enums"]["app_role"]
      }
      is_admin: { Args: never; Returns: boolean }
      tutor_can_see_student: {
        Args: { p_student_id: string }
        Returns: boolean
      }
      tutor_id_for_current_user: { Args: never; Returns: string }
    }
    Enums: {
      app_role:
        | "tech"
        | "jefe_comercial"
        | "comercial"
        | "administracion"
        | "tutor"
      cash_method: "transferencia" | "efectivo"
      certificate_status: "pendiente" | "emitido" | "anulado"
      contact_type: "correo" | "llamada" | "videollamada" | "whatsapp" | "otro"
      contract_status: "borrador" | "enviado" | "firmado" | "anulado"
      enrollment_status:
        | "pendiente"
        | "validada"
        | "activa"
        | "finalizada"
        | "cancelada"
      financer: "alma" | "sabadell" | "sequra" | "esmera"
      followup_student_status:
        | "activo"
        | "pendiente"
        | "sin_actividad"
        | "riesgo_abandono"
        | "finalizado"
      lead_source:
        | "web"
        | "referido"
        | "redes_sociales"
        | "llamada_entrante"
        | "evento"
        | "otro"
        | "meta_ads"
        | "organico"
        | "agente_web"
      lead_status:
        | "nuevo"
        | "contactado"
        | "cualificado"
        | "convertido"
        | "descartado"
      notification_type:
        | "nueva_venta"
        | "matricula_pendiente"
        | "tutor_asignado"
        | "alumno_inactivo"
        | "curso_finalizado"
        | "certificado_pendiente"
      payment_type: "contado" | "financiado" | "mixto"
      student_status:
        | "en_formacion"
        | "seguimiento_activo"
        | "riesgo_abandono"
        | "sin_actividad"
        | "finalizado"
        | "expediente_cerrado"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      app_role: [
        "tech",
        "jefe_comercial",
        "comercial",
        "administracion",
        "tutor",
      ],
      cash_method: ["transferencia", "efectivo"],
      certificate_status: ["pendiente", "emitido", "anulado"],
      contact_type: ["correo", "llamada", "videollamada", "whatsapp", "otro"],
      contract_status: ["borrador", "enviado", "firmado", "anulado"],
      enrollment_status: [
        "pendiente",
        "validada",
        "activa",
        "finalizada",
        "cancelada",
      ],
      financer: ["alma", "sabadell", "sequra", "esmera"],
      followup_student_status: [
        "activo",
        "pendiente",
        "sin_actividad",
        "riesgo_abandono",
        "finalizado",
      ],
      lead_source: [
        "web",
        "referido",
        "redes_sociales",
        "llamada_entrante",
        "evento",
        "otro",
        "meta_ads",
        "organico",
        "agente_web",
      ],
      lead_status: [
        "nuevo",
        "contactado",
        "cualificado",
        "convertido",
        "descartado",
      ],
      notification_type: [
        "nueva_venta",
        "matricula_pendiente",
        "tutor_asignado",
        "alumno_inactivo",
        "curso_finalizado",
        "certificado_pendiente",
      ],
      payment_type: ["contado", "financiado", "mixto"],
      student_status: [
        "en_formacion",
        "seguimiento_activo",
        "riesgo_abandono",
        "sin_actividad",
        "finalizado",
        "expediente_cerrado",
      ],
    },
  },
} as const

// Legacy type aliases — kept for backwards compatibility with hand-written code
export type AppRole = Database["public"]["Enums"]["app_role"]
export type StudentStatus = Database["public"]["Enums"]["student_status"]
export type EnrollmentStatus = Database["public"]["Enums"]["enrollment_status"]
export type LeadStatus = Database["public"]["Enums"]["lead_status"]
export type LeadSource = Database["public"]["Enums"]["lead_source"]
export type ContractStatus = Database["public"]["Enums"]["contract_status"]
export type PaymentType = Database["public"]["Enums"]["payment_type"]
export type CashMethod = Database["public"]["Enums"]["cash_method"]
export type Financer = Database["public"]["Enums"]["financer"]
export type ContactType = Database["public"]["Enums"]["contact_type"]
export type FollowupStudentStatus = Database["public"]["Enums"]["followup_student_status"]
export type CertificateStatus = Database["public"]["Enums"]["certificate_status"]
export type NotificationType = Database["public"]["Enums"]["notification_type"]
export type LeadContactType = "llamada_saliente" | "llamada_entrante" | "email" | "whatsapp" | "reunion" | "otro"
